### ISSUE TITLE
No such file or directory GitCommitTracker.sh when I open up a new shell

### ISSUE THREAD

**Issue by scottnm** [kassandrasmith/ACommitADay#1]
exact error is
/Users/scottmunro/.zshrc:167: no such file or directory: ./GitCommitTracker.sh

Here's what happens with the setup script if it helps

Hello, scottmunro.
Please enter your github login e-mail and press [ENTER]
scottmunro@utexas.edu
Please enter the message you would like to see if you HAVE made a commit today  and press [ENTER]:
You did it
Please enter the message you would like to see if you HAVE NOT made a commit today and press [ENTER]: 
You CAN do it

Would you like to update the repository directory? [y/n]:
y
Finding git repositories. . . This may take a while!

```
grep: /Users/scottmunro/BrokenRepos.txt: No such file or directory
rm: /Users/scottmunro/BrokenRepos.txt: No such file or directory
All Done! Working repositories listed in RepositoryDirectory.txt
done!

```

**Comment by kassandrasmith** [comment]
Thanks for the issue Scottnm! The script was looking for a file that I had locally but isn't necessary for it to function. It should work now.
